#ddev-gitpod-generated
router_http_port: 8080
router_https_port: 8443
use_dns_when_possible: false

additional_fqdns:
- 8080-sccdevelope-evolvedrupa-l4nu5dx6uwp.ws-us104.gitpod.io
- 8025-sccdevelope-evolvedrupa-l4nu5dx6uwp.ws-us104.gitpod.io
- 8036-sccdevelope-evolvedrupa-l4nu5dx6uwp.ws-us104.gitpod.io
